-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: b08f834d65fed15e25cbe3073df7ff457459801a
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E265,E309,E501']
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: git@github.com:asottile/reorder_python_imports
    sha: ab361ca1e4dfaeea0c4eab464c799e02cb306ab3
    hooks:
    -   id: reorder-python-imports
        exclude: ^bench/
